version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sabores-mysql-staging
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-staging_root_password}
      MYSQL_DATABASE: sabores_conectados_staging
    ports:
      - "3306:3306"
    volumes:
      - mysql_staging_data:/var/lib/mysql
      - ./config/mysql/staging:/etc/mysql/conf.d
    networks:
      - sabores-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  eureka-server:
    image: ${DOCKER_USERNAME}/eureka-server:${VERSION:-latest}
    container_name: eureka-server-staging
    ports:
      - "8761:8761"
    networks:
      - sabores-staging-network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=staging
      - EUREKA_SERVER_PORT=8761
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cardapio-service:
    image: ${DOCKER_USERNAME}/cardapio-service:${VERSION:-latest}
    container_name: cardapio-service-staging
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cardapio?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-staging_root_password}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - sabores-staging-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  pedidos-service:
    image: ${DOCKER_USERNAME}/pedidos-service:${VERSION:-latest}
    container_name: pedidos-service-staging
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pedidos?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-staging_root_password}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - sabores-staging-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  pagamentos-service:
    image: ${DOCKER_USERNAME}/pagamentos-service:${VERSION:-latest}
    container_name: pagamentos-service-staging
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pagamentos?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-staging_root_password}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - sabores-staging-network
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    image: ${DOCKER_USERNAME}/gateway:${VERSION:-latest}
    container_name: gateway-staging
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=staging
    networks:
      - sabores-staging-network
    depends_on:
      eureka-server:
        condition: service_healthy
      cardapio-service:
        condition: service_healthy
      pedidos-service:
        condition: service_healthy
      pagamentos-service:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Monitoramento
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-staging
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sabores-staging-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-staging
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_staging_data:/var/lib/grafana
    networks:
      - sabores-staging-network
    restart: unless-stopped

volumes:
  mysql_staging_data:
  grafana_staging_data:

networks:
  sabores-staging-network:
    driver: bridge
