groups:
- name: sabores-conectados-alerts
  rules:
  # Alertas de CPU
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

  # Alertas de Memória
  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

  # Alertas de Disk
  - alert: HighDiskUsage
    expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High disk usage detected"
      description: "Disk usage is above 90% for more than 5 minutes on {{ $labels.instance }}"

  # Alertas de Aplicação
  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service is down"
      description: "Service {{ $labels.job }} is down on {{ $labels.instance }}"

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 10% for {{ $labels.job }} on {{ $labels.instance }}"

  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is above 2 seconds for {{ $labels.job }} on {{ $labels.instance }}"

  # Alertas de Banco de Dados
  - alert: MySQLDown
    expr: mysql_up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MySQL is down"
      description: "MySQL database is down on {{ $labels.instance }}"

  - alert: MySQLSlowQueries
    expr: mysql_global_status_slow_queries > 10
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "MySQL slow queries detected"
      description: "MySQL has more than 10 slow queries on {{ $labels.instance }}"

  # Alertas de Eureka
  - alert: EurekaServiceUnavailable
    expr: eureka_registered_instances < 1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Eureka service unavailable"
      description: "No instances registered in Eureka for {{ $labels.service }}"
